### ISSUE TITLE
Where is 'set_ams()'?

### ISSUE THREAD

**Issue by daviduarte** [grei-ufc/pade#1]
I installed pade from GitHub, and tried to run the example code below:

```
from pade.misc.utility import display_message
from pade.misc.common import set_ams, start_loop
from pade.core.agent import Agent
from pade.acl.aid import AID


class AgenteHelloWorld(Agent):
    def __init__(self, aid):
        super(AgenteHelloWorld, self).__init__(aid=aid, debug=False)
        display_message(self.aid.localname, 'Hello World!')

if __name__ == '__main__':

    set_ams('localhost', 8000, debug=False)

    agents = list()

    agente_hello = AgenteHelloWorld(AID(name='agente_hello'))
    agente_hello.ams = {'name': 'localhost', 'port': 8000}
    agents.append(agente_hello)

    start_loop(agents, gui=True)
```

Therefore, the following error message arrive: 

```
Traceback (most recent call last):
  File "kkk.py", line 2, in <module>
    from pade.misc.common import set_ams, start_loop
ImportError: cannot import name 'set_ams
```

I looked up the file common.py, in pade.misc.common path, for the function 'set_ams()', but I wasn't able to find it. This may be the error source?

**Comment by SouGit** [comment]
I have the same issue. When I tried the following code:
```
from pade.misc.utility import display_message
from pade.misc.common import PadeSession
from pade.core.agent import Agent
from pade.acl.aid import AID


class AgenteHelloWorld(Agent):
    def __init__(self, aid):
        super(AgenteHelloWorld, self).__init__(aid=aid)
        display_message(self.aid.localname, 'Hello World!')


def config_agents():

    agents = list()

    agente_hello = AgenteHelloWorld(AID(name='agente_hello'))
    agents.append(agente_hello)

    s = PadeSession()
    s.add_all_agents(agents)
    s.register_user(username='lucassm', email='lucas@gmail.com', password='12345')

    return s

if __name__ == '__main__':

    s = config_agents()
    s.start_loop()

```

I got this error:
_**self.performative = performative.lower()
AttributeError: Can't set arbitrary attributes on Element**_

**Comment by lucassm** [comment]
Hello @daviduarte! Are you using a virtual environment with the most actual version of pade?
I recommend that you use anaconda python distribution, create a clean virtual environment, them clone the github repository and install with python setup.py install. Are you following these steps?
Sorry for the delay in answering, but I was a bit busy these days.

**Comment by lucassm** [comment]
@SouGit are you using a clean anaconda virtual environment? Some users report this same error that was solved with a new and clean virtual environment.

**Comment by lucassm** [comment]
> I have the same issue. When I tried the following code:
> 
> ```
> from pade.misc.utility import display_message
> from pade.misc.common import PadeSession
> from pade.core.agent import Agent
> from pade.acl.aid import AID
> 
> 
> class AgenteHelloWorld(Agent):
>     def __init__(self, aid):
>         super(AgenteHelloWorld, self).__init__(aid=aid)
>         display_message(self.aid.localname, 'Hello World!')
> 
> 
> def config_agents():
> 
>     agents = list()
> 
>     agente_hello = AgenteHelloWorld(AID(name='agente_hello'))
>     agents.append(agente_hello)
> 
>     s = PadeSession()
>     s.add_all_agents(agents)
>     s.register_user(username='lucassm', email='lucas@gmail.com', password='12345')
> 
>     return s
> 
> if __name__ == '__main__':
> 
>     s = config_agents()
>     s.start_loop()
> ```
> 
> I got this error:
> _**self.performative = performative.lower() AttributeError: Can't set arbitrary attributes on Element**_

**Comment by SakshiiSharmaa** [comment]
> I have the same issue. When I tried the following code:
> 
> ```
> from pade.misc.utility import display_message
> from pade.misc.common import PadeSession
> from pade.core.agent import Agent
> from pade.acl.aid import AID
> 
> 
> class AgenteHelloWorld(Agent):
>     def __init__(self, aid):
>         super(AgenteHelloWorld, self).__init__(aid=aid)
>         display_message(self.aid.localname, 'Hello World!')
> 
> 
> def config_agents():
> 
>     agents = list()
> 
>     agente_hello = AgenteHelloWorld(AID(name='agente_hello'))
>     agents.append(agente_hello)
> 
>     s = PadeSession()
>     s.add_all_agents(agents)
>     s.register_user(username='lucassm', email='lucas@gmail.com', password='12345')
> 
>     return s
> 
> if __name__ == '__main__':
> 
>     s = config_agents()
>     s.start_loop()
> ```
> 
> I got this error:
> _**self.performative = performative.lower() AttributeError: Can't set arbitrary attributes on Element**_

i am also getting this problem. Did you got any soluion to this?
