### ISSUE TITLE
Is it possible to use pade in android and ios application?

### ISSUE THREAD

**Issue by lmcompany** [grei-ufc/pade#11]
Hello there, Is it possible to use pade agents in android and ios app?
And if the answer is yes, can i use it as a library?
Actualy i want to develope an agent base app in both platforms and want to know that is it possible  to add pade as a library to my project?
Thank's for your help.

**Comment by lucassm** [comment]
Hello, @lmcompany . Sorry for the late answer, many work to do in this days... Now I have more free time to dedicate to PADE.
Answering your question, unfortunately PADE does not run in mobile platforms like Android and IOS.
PADE was developed to run primarily in PC platforms like Linux, MAC and Windows.
But if the device has the possibility to run Python 3.7 we can build a minimal client to run in this kind of mobile platform.
PADE is a Open Source project and is open to collaboration. So if you or your University or your Business are planing to use Multi-agent Systems in mobile, we can help you in doing this with PADE.
