### ISSUE TITLE
Error while running the hello world pade example 

### ISSUE THREAD

**Issue by YasinEnigma** [grei-ufc/pade#17]
Hi, I am using ubuntu 18.10, installed PADE by pip method, and tried running the first hello world example and I get this error:

* Serving Flask app "pade.web.flask_server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/pade/core/new_ams.py", line 1, in <module>
    from pade.core.agent import Agent_
ImportError: No module named pade.core.agent
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/pade/core/sniffer.py", line 1, in <module>
    from pade.core.agent import Agent
ImportError: No module named pade.core.agent
Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    from pade.misc.utility import display_message, start_loop
  File "/home/user/pade.py", line 1, in <module>
ImportError: No module named misc.utility

What could be the reason?

**Comment by lucassm** [comment]
Hello @YasinEnigma, actually the pip method wasn't working, but I have made an update today and fixed some behaviors.

Try to install again via pip install, and see if it works. If it doesn't work, clone the Github repository and run a python setup.py install.

Don't forget to read the README.md before launching a PADE example.
Regards.
