### ISSUE TITLE
Issue during PADE install under Windows

### ISSUE THREAD

**Issue by kridenberg** [grei-ufc/pade#30]
Hi, this error occurs when I try to install PADE with an Anaconda environment. It is something (as I think) with encoding. Thx.

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    long_description = fh.read()
  File "C:\Userspace\Anaconda\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1736: character maps to <undefined>

**Comment by lucassm** [comment]
Hello, @kridenberg.

From where are you installing PADE? github or pip?
What version of python are you using? The recommended is python 3.7.
Can you put the commands that you are using to install it?
