### ISSUE TITLE
Removes the `start-runtime` option

### ISSUE THREAD

**Issue by filipesaraiva** [grei-ufc/pade#42]
Currently PADE must be run using the `start-runtime` option. This sounds unnecessary.

We could just use `pade` for default and the runtime environment will be started.

**Comment by lucassm** [comment]
@filipesaraiva I think that this issue can be closed.

**Comment by filipesaraiva** [comment]
Sure, this issue would be closed automatically if we had merged #44 to the main branch (currently, `master` branch).

But no problem, let's do manually.
