### ISSUE TITLE
Guia desatualizado

### ISSUE THREAD

**Issue by kellydosocorro** [grei-ufc/pade#5]
O guia de usuário contendo a documentação e disponibilizado em (https://pade-docs-en.readthedocs.io/en/latest/) e (https://pade.readthedocs.io/pt/latest/) para a compreensão das funcionalidades do framework está desatualizado em relação a este, inviabilizando a aplicação dos exemplos fornecidos na versão atual do PADE.

**Comment by franlu** [comment]
I started to use it... the docs need an update as soon as possible.
